{
    "fix": "https://github.com/guidovranken/python-library-fuzzers/commit/e57e43d68d5f5c9394860fefd1df62eae56ff800",
    "verify": "0",
    "localId": 58510,
    "project": "python-library-fuzzers",
    "fuzzer": "libfuzzer",
    "sanitizer": "asan",
    "crash_type": "Heap-buffer-overflow WRITE 1",
    "severity": "High",
    "report": {
        "comments": [
            {
                "projectName": "oss-fuzz",
                "localId": 58510,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1682870136,
                "content": "Detailed Report: https://oss-fuzz.com/testcase?key=4723623318650880\n\nProject: python3-libraries\nFuzzing Engine: libFuzzer\nFuzz Target: fuzzer-ast\nJob Type: libfuzzer_asan_python3-libraries\nPlatform Id: linux\n\nCrash Type: Heap-buffer-overflow WRITE 1\nCrash Address: 0x62a0000591f4\nCrash State:\n  tok_get_normal_mode\n  _PyTokenizer_Get\n  _PyPegen_tokenize_full_source_to_check_for_errors\n  \nSanitizer: address (ASAN)\n\nRecommended Security Severity: High\n\nRegressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_python3-libraries&range=202304180604:202304200604\n\nReproducer Testcase: https://oss-fuzz.com/download?testcase_id=4723623318650880\n\nIssue filed automatically.\n\nSee https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.\nWhen you fix this bug, please\n  * mention the fix revision(s).\n  * state whether the bug was a short-lived regression or an old bug in any stable releases.\n  * add any other useful information.\nThis information can help downstream consumers.\n\nIf you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.\n\nThis bug is subject to a 90 day disclosure deadline. If 90 days elapse\nwithout an upstream patch, then the bug report will automatically\nbecome visible to the public.",
                "descriptionNum": 1
            },
            {
                "projectName": "oss-fuzz",
                "localId": 58510,
                "sequenceNum": 1,
                "commenter": {
                    "userId": "2408361860",
                    "displayName": "guido...@gmail.com"
                },
                "timestamp": 1682872619,
                "content": "https://github.com/python/cpython/issues/104016"
            },
            {
                "projectName": "oss-fuzz",
                "localId": 58510,
                "sequenceNum": 2,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1682880986,
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "Disclosure-2023-07-31"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 58510,
                "sequenceNum": 3,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1683045736,
                "content": "ClusterFuzz testcase 4723623318650880 is verified as fixed in https://oss-fuzz.com/revisions?job=libfuzzer_asan_python3-libraries&range=202305010614:202305020605\n\nIf this is incorrect, please file a bug on https://github.com/google/oss-fuzz/issues/new",
                "amendments": [
                    {
                        "fieldName": "Status",
                        "newOrDeltaValue": "Verified",
                        "oldValue": "New"
                    },
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "ClusterFuzz-Verified"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 58510,
                "sequenceNum": 4,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1683053397,
                "content": "This bug has been fixed. It has been opened to the public.\n\n- Your friendly Sheriffbot",
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "-restrict-view-commit"
                    }
                ]
            }
        ]
    },
    "fix_commit": "e57e43d68d5f5c9394860fefd1df62eae56ff800",
    "repo_addr": "https://github.com/guidovranken/python-library-fuzzers.git"
}